name: 'Set up Rust'
description: 'Install a Rust toolchain and add it to the PATH'
author: 'Héctor Ramón'
inputs:
  rust-version:
    description: 'The toolchain name, such as stable, nighly, or 1.8.0'
    default: '1.37.0'
runs:
  using: 'node12'
  main: 'lib/main.js'
